//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forncecedor_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORNECEDOR
    {
        public int ID_FORNECEDOR { get; set; }
        public string NOME { get; set; }
        public string CNPJ { get; set; }
        public string ENDERECO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string SITUACAO { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
    }
}
